apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    run: app-bar
spec:
- port: 8080
  targetPort: 80
  protocol: TCP
  name: http
selector:
  run: app-bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  selector:
    matchLabels:
      run: app-bar
  replicas: 2
  template:
    metadata:
      labels:
        run: app-bar
    spec:
      containers:
      - name: bar
        image: bar:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

